### ISSUE TITLE
Databinding seems to break SurfaceDuoLayout

### ISSUE THREAD

**Issue by neatorobito** [microsoft/surface-duo-sdk#35]
I'm working on a custom launcher for the Duo and I've setup data binding within a relatively simple project. When I add binding to the activity however, it breaks the posture change detection. I get the same single screen layout regardless of the device's posture.

## Without databinding in Main Activity
MainActivity.kt
```
class MainActivity : AppCompatActivity() {
    private val vm: CoreViewModel by viewModels()

//    lateinit var singleBinding: FragmentHomeSingleBindingImpl
//    lateinit var dualStartBinding: HomeDualStartBindingImpl
//    lateinit var dualEndBinding: HomeDualEndBindingImpl

    lateinit private var systemTimeBr: SystemTimeBroadcastReceiver

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        
//        singleBinding = DataBindingUtil.setContentView(this, R.layout.fragment_home_single)
//        dualStartBinding = DataBindingUtil.setContentView(this, R.layout.home_dual_start)
//        dualEndBinding = DataBindingUtil.setContentView(this, R.layout.home_dual_end)

//        singleBinding.lifecycleOwner = this
//        dualStartBinding.lifecycleOwner = this
//        dualEndBinding.lifecycleOwner = this

//        singleBinding.setVariable(BR.corevm, vm)
//        dualStartBinding.setVariable(BR.corevm, vm)
//        dualEndBinding.setVariable(BR.corevm, vm)

        window.addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS)
    }
...
}
```
activity_main.xml
```
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android">

    <com.microsoft.device.dualscreen.layouts.SurfaceDuoLayout
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:animateLayoutChanges="true"
        app:single_screen_layout_id="@layout/fragment_home_single"
        app:dual_screen_start_layout_id="@layout/fragment_home_dual_start"
        app:dual_screen_end_layout_id="@layout/fragment_home_dual_end">

    </com.microsoft.device.dualscreen.layouts.SurfaceDuoLayout>

</layout>
```

### Single screen mode
![image](https://user-images.githubusercontent.com/3013405/128264117-86a47b96-b6ce-420a-ab61-64e18f508cbd.png)
This behavior is correct.

### Dual screen mode
![image](https://user-images.githubusercontent.com/3013405/128264150-42ba113a-5917-4b3a-b25e-83d8108ec7a9.png)
This behavior is correct. This is what we should see when unfolded.

### Single screen mode
![image](https://user-images.githubusercontent.com/3013405/128262710-7b54f897-7730-4fbb-ba78-ea0406a0bb6f.png)
This behavior is correct.

### Dual screen mode
![image](https://user-images.githubusercontent.com/3013405/128262800-309f16b7-3b13-4b7e-be3c-d212acae9835.png)
This behavior is incorrect, I'm getting the same single screen UI spanned. 

All I've done is add these lines back (uncomment) in MainActivity.kt:
` singleBinding = DataBindingUtil.setContentView(this, R.layout.fragment_home_single)`
`singleBinding.lifecycleOwner = this`
`singleBinding.setVariable(BR.corevm, vm)`

And in fragment_home_single.xml

```
    <data>
        <variable
            name="corevm"
            type="fyi.meld.duo.viewmodels.CoreViewModel" />
    </data>
```

```
    <TextView
        android:id="@+id/time_view"
        ...
        android:text="@{corevm.clockData.time}"
        ... />

    <TextView
        android:id="@+id/meridian_indicator_view"
        ...
        android:text="@{corevm.clockData.meridian_indicator}"
        ... />

    <TextView
        android:id="@+id/date_view"
        ...
        android:text="@{corevm.clockData.date}"
        ... />
```

## Other notes
* [The full repository is here](https://github.com/neatorobito/Fluent-Duo-Launcher). Be sure to check out the **screen_transition_bug** branch. You can try repro-ing it the same way with the full project.
* I figure I should probably be setting up the binding in the HomeSingleFragment, but I just haven't gotten around to it yet.
* I see that there is some special [handling required for fragments to support screen state transitions](https://docs.microsoft.com/en-us/dual-screen/android/api-reference/dualscreen-library/fragment-handler/fragment-manager-state-handler?tabs=kotlin), but I'm also able to repro this exact issue regardless of whether or not the inputs to SurfaceDuoLayout are fragments or just regular old layouts.

Please let me know if there's more context I can provide.

Thanks!

**Comment by CristianVerdes** [comment]
Hello Mark!

Thank you for reporting this to us. We will look into it and provide a fix as soon as possible.

Have a great day!

**Comment by neatorobito** [comment]
I ended up re-writing the app to use a custom layout based on the alpha 10 release of the WindowManager APIs.

**Comment by ancirja-m** [comment]
Hello Mark,

Sorry for the late response. Unfortunately, our SurfaceDuoLayout doesn't support direct databinding, but there is a workaround for this.
You can create some xml files for every posture (single screen, dual screen start, dual screen end) and inside these xml files you can use fragments. With these fragments you can use databinding without any problems.

I checked your repo and I made some modifications, and now it's working. If you give me access again, I can create a branch with these modifications.

Related to databinding for SurfaceDuoLayout, we'll try to find a solution for it.

Have a great day!

**Comment by neatorobito** [comment]
Hi Andrei,

That approach is what I ended up doing with the rewrite to use WindowManager I talked about. 

[Here's the motionlayout file.](https://github.com/neatorobito/Fluent-Duo-Launcher/blob/main/app/src/main/res/xml/fragment_home_scene.xml)
[And here's the code to do transitions.](https://github.com/neatorobito/Fluent-Duo-Launcher/blob/main/app/src/main/java/fyi/meld/duo/fragments/HomeFragment.kt#L59)

I appreciate the response. I have some other questions that I'll probably post in discussions.
