### ISSUE TITLE
Splitting Examples

### ISSUE THREAD

**Issue by supertx2** [microsoft/surface-duo-sdk#41]
Hi,

In https://docs.microsoft.com/en-us/dual-screen/introduction you guys talk about Masking and Splitting but I didn't find any examples how to 'Split'. Is this something that we have to manually do or some feature that we can toggle?

**Comment by CesarValiente** [comment]
You totally can achieve that, but you will have to think differently regarding how you show the content to users that have foldable devices. The key is to enhance your current app and adapt it to provide a better experience for users that have those devices. For instance, as a manga reader, you could take advantage of having two different displays to show the pages of manga, one on each side.

As an example:

![image](https://user-images.githubusercontent.com/1050785/136772056-49f8b1f9-e073-4f2a-bb03-b8506691ecee.png)

Source: https://www.reddit.com/r/Surface/comments/ium243/surface_duo_is_probably_the_perfect_comicmanga/?utm_source=share&utm_medium=web2x&context=3

This is also what Amazon Kindle app does on Surface Duo:

![image](https://user-images.githubusercontent.com/1050785/136772249-7aecd299-0c07-45d7-bf6e-2a77bf8aeaa8.png)

**Comment by supertx2** [comment]
I see, splitting the manga was my initial thought,
When I saw the Splitting in the documentation I thought that we had some easy way to achieve that.
Thanks for the help!
