### ISSUE TITLE
wm-utils 1.0.0-beta4 is not published

### ISSUE THREAD

**Issue by beparker** [microsoft/surface-duo-sdk#78]
Tabs 1.0.0-beta4 relies on wm-utils 1.0.0-beta4 https://repo.maven.apache.org/maven2/com/microsoft/device/dualscreen/tabs/1.0.0-beta4/tabs-1.0.0-beta4.pom but its not published. 

wm-utils only goes up to 1.0.0-beta3/ https://repo.maven.apache.org/maven2/com/microsoft/device/dualscreen/wm-utils/

**Comment by CesarValiente** [comment]
Hi @beparker **thanks a lot** for reporting the issue! 
For some reason we missed the publication of this artifact. We have just published it, and it should be available on Maven Central on a few minutes (it will take more time to be visible on Maven Central Repository search).
